import Head from "next/head";
import Image from "next/image";
import profilePic from "../public/janse.jpg";

import svelteIco from "../public/svelte_ico.svg";
import vueIco from "../public/vue_ico.svg";
import nextLogo from "../public/next_ico.svg";


let fadeIn = true

const fadeLogos = () => {
  if (fadeIn) {
    fadeIn = false
  }
  else {
    fadeIn = true
  }
};
setInterval(() => fadeLogos(), 2000)

export default function Home() {
  return (
    <div>
      <Head>
        <title>I&apos;m a cute little tab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="m-4 w-auto shadow rounded-[6px]">
        <div className="flex flex-row-reverse items-center p-16 rounded-t-[6px] h-[45vh] bg-gradient-to-r from-cyan-500 to-blue-500">
          <p className="font-black text-white text-8xl">
            Well, <br />
            hello there.
          </p>
        </div>
        <div className="flex flex-row">
          <div className="h-96 w-[35vw] relative shrink-0">
            <Image
              src={profilePic}
              alt="This is my beautiful beautiful face"
              layout="fill"
              objectFit="cover"
              priority="ture"
            />
          </div>
          <div className="flex flex-col p-10 justify-center divide-y-4">
            <h1 className="text-6xl pb-2">Hey, I&apos;m Janse</h1>
            <p className="text-xl pt-1">
              Lorem ipsum blablabla soon there will be some nice text here. If
              you&apos;re a good UI designer and your eyes are bleeding right
              now I&apos;m deeply sorry.
            </p>
          </div>
        </div>
        <div className="flex flex-col items-center bg-gray-700">
          <p className="text-white">I ❤️</p>
          <div
            id="experience-slide"
            className={
              fadeIn
                ? "opacity-100 transition transition-opacity ease-in-out duration-300"
                : "opacity-0 transition transition-opacity ease-in-out duration-300"
            }
          >
            {/*TODO: Cycling through icons with fade in/out*/}
            {/*TODO: Style experience slide*/}
            <Image src={svelteIco} width="60" height="60" alt="Svelte Icon" />
            <Image src={vueIco} width="60" height="60" alt="Vue Icon" />
            <Image src={nextLogo} width="60" height="60" alt="Next Icon" />
          </div>
        </div>
        <div className="flex flex-row items-center p-16 rounded-b-[6px] h-[45vh] bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
          <p className="font-black text-white text-8xl">
            Stay <br />
            in touch.
          </p>
          <div>{/*TODO: Create grid with Social Media and Mail Contact*/}</div>
        </div>
      </div>
    </div>
  );
}
